apiVersion: v1
kind: Pod
metadata:
  name: demo-opc-strategies
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app-strategy
    environment: {{ .Values.environment }}

spec:
  containers:
    - name: demo-opc-strategies-container
      image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
      env:
      - name: ConfigurationName
        value: "This is {{ .Values.environment }}"
      - name: Environment__Name
        value: "{{ .Values.environment }}"
  imagePullSecrets:
  - name: {{ .Values.pullSecret.name }}
  volumes:
    - name: packingConfig
      configMap:
        name: demo-central-packing-config
        items:
        - key: "line.packing.properties"
          path: "line.packing.properties"
    - name: processingConfig
      configMap:
        name: demo-central-processing-config
        items:
        - key: "line.processing.properties"
          path: "line.processing.properties"
