apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-opc-strategies
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app-strategy
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: demo-app-strategy
  template:
    metadata:
      labels:
        app: demo-app-strategy
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: demo-opc-strategies-container
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: ConfigurationName
          value: "This is {{ .Values.environment }}"
        - name: Environment__Name
          value: "{{ .Values.environment }}"
        volumeMounts:
        - mountPath: /config/packing
          name: packingconfig
        - mountPath: /config/processing
          name: processingconfig
      imagePullSecrets:
      - name: {{ .Values.pullSecret.name }}
      volumes:
      - name: packingconfig
        configMap:
          name: packing-config
      - name: processingconfig
        configMap:
          name: processing-config

