apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-opc-strategies
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app-strategy
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: demo-app-strategy
  template:
    metadata:
      labels:
        app: demo-app-strategy
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: demo-opc-strategies-container
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: ConfigurationName
          value: "This is {{ .Values.environment }}"
        - name: Configuration__Directory
          value: "{{ .Values.lineConfiguration.configurationDirectory }}"
        - name: Configuration__UseWatcher
          value: "{{ .Values.lineConfiguration.useWatcher }}"
        - name: Packing__Host
          value: "{{ .Values.lineConfiguration.packing.host }}"
        - name: Packing__Port
          value: "{{ .Values.lineConfiguration.packing.port }}"
        - name: Packing__File
          value: "{{ .Values.lineConfiguration.packing.file }}"
        - name: Processing__Host
          value: "{{ .Values.lineConfiguration.processing.host }}"
        - name: Processing__Port
          value: "{{ .Values.lineConfiguration.processing.port }}"
        - name: Processing__File
          value: "{{ .Values.lineConfiguration.processing.file }}"
        - name: Environment__Name
          value: "{{ .Values.environment }}"
        volumeMounts:
        - mountPath: /app/lines/packing
          name: packingconfig
          readOnly: false
        - mountPath: /app/lines/processing
          name: processingconfig
          readOnly: false
      imagePullSecrets:
      - name: {{ .Values.pullSecret.name }}
      volumes:
      - name: packingconfig
        configMap:
          name: packing-config
      - name: processingconfig
        configMap:
          name: processing-config

