apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.namespace }}
data: 
  .dockerconfigjson: {{ .Values.pullSecret.content }}
type: kubernetes.io/dockerconfigjson