apiVersion: v1
kind: Pod
metadata:
  name: demo-opc-strategies
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app-strategy
    environment: {{ .Values.environment }}

spec:
  containers:
    - name: demo-opc-strategies-container
      image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
      volumeMounts:
      - mountPath: /config
        name: packingconfig
      env:
      - name: ConfigurationName
        value: "This is {{ .Values.environment }}"
      - name: Environment__Name
        value: "{{ .Values.environment }}"

#      volumeMounts:
#      - name: config
#        mountPath: "/config"
#        readOnly: false
#      - name: processingConfig
#        mountPath: "/config/processing"
#        readOnly: false
  volumes:
    - name: packingconfig
      configMap:
        name: packing-config
  imagePullSecrets:
  - name: {{ .Values.pullSecret.name }}
#  volumes:
#    - name: config
#      configMap:
#        name: packing-config
#        items:
#        - key: "line"
#          path: "line"
#    - name: processingConfig
#      configMap:
#        name: processing-config
#        items:
#        - key: "line.processing.properties"
#          path: "line.processing.properties"
