# Default values for factory-strat-1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "demo-central-oper"
environment: "specific"

image:
  repository: "cgcregistry1.azurecr.io"
  name: "busybox"
  tag: "001"

pullSecret:
  content: "ewoJImF1dGhzIjogewoJCSJjZ2NyZWdpc3RyeTEuYXp1cmVjci5pbyI6IHsKCQkJImF1dGgiOiAiWTJkalVtVm5hWE4wY25reE9tOTVSa1kxUWprclRVcFdNbGt5WlZrdk1YRnpQV05uYkZwQlpHUmhkbFowIgoJCX0KCX0KfQ=="
  name: "regcred"

strategy:
  processing:   
    productName: "none"
    recipe: "0"
    modification: "0"
  packing:
    formFactor: "0"
    size: "0"
